version: 1.0.{build}

environment:
  matrix:
    - job_name: Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
      APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC50zi/cXG9E0YLZQWAGoDmZ9gEy9mtbdWIHv7WmyGErrC9DPLNS8p/G4nFzN9zPfr7WNxyr9SXOA0o1RISOcYn7vMXK0IZFuE5hetZeJrySRC6zU7okEW9cVE77XA6n45jB0oTmqq+GWE87q9zQL/+eob8pwelT2UD5h3UPq5n6mqARum99M6+NcZiKMYNGgN1N3gM51Bpu6XNSdFQzgQn8nNGjdIRQoG0Kv9QBf/zUq+ACoEtYQTpu5hoY4WKm07ZRMDAMMNPeg0bt38fw5X37ZHQNY7QklMXPGMNp1EVzE/Rg51FK+P8LI0TIxSPctl14FvHNzjeCHB7vha1M7oT
      APPVEYOR_SSH_BLOCK: true

platform:
 - x86

test: off

for:
# ======================================
#      Windows
# ======================================
-
  matrix:
    only:
    - job_name: Windows

  build_script:
   - python setup.py
   - build.bat

  install:
   - git submodule update --init --recursive


 # ======================================
#      Linux
# ======================================
-
  matrix:
    only:
    - job_name: Linux
  
  install:
   - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
   - sudo dpkg --add-architecture i386
   - sudo mkdir -pm755 /etc/apt/keyrings
   - sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
   - sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
   - sudo apt update
   - sudo apt install --install-recommends -y winehq-stable
   - git submodule update --init --recursive

  build_script:
   - wine --version
   - python3 setup.py
   - rm -Rf ./wine
   - export WINEPREFIX=~/.wine32
   - export WINEARCH=win32 
   - wine wineboot
   - ls
   - wine reg add HKLM\\SOFTWARE\\Microsoft\\VisualStudio\\6.0\\Setup /v VsCommonDir /t REG_SZ /d Z:\\home\\appveyor\\projects\\gta2-re-oo2fq\\3rdParty\\gta2_re_compile_tools\\Common
   - xvfb-run wine cmd /c build.bat
