version: 1.0.{build}

environment:
  matrix:
    - job_name: Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204

platform:
 - x86

test: off

for:
# ======================================
#      Windows
# ======================================
-
  matrix:
    only:
    - job_name: Windows

  build_script:
   - python setup.py
   - build.bat

  install:
   - git submodule update --init --recursive


 # ======================================
#      Linux
# ======================================
-
  matrix:
    only:
    - job_name: Linux
  
  install:
   - sudo apt-get install -y xvfb
   - xvfb-run
   - sudo dpkg --add-architecture i386
   - sudo mkdir -pm755 /etc/apt/keyrings
   - sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
   - sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
   - sudo apt update
   - sudo apt install --install-recommends -y winehq-stable
   - git submodule update --init --recursive

  build_script:
   - wine --version
   - python3 setup.py
   - rm -Rf ./wine
   - export WINEPREFIX=~/.wine32
   - export WINEARCH=win32 
   - wine wineboot
   - ls
   - wine reg add HKLM\\SOFTWARE\\Microsoft\\VisualStudio\\6.0\\Setup /v VsCommonDir /t REG_SZ /d Z:\home\appveyor\projects\gta2-re-oo2fq\3rdParty\gta2_re_compile_tools\Common\
   - wine cmd /c build.bat
