name: CI

on:
  push:
    branches: [ci-tests]
  pull_request:
    branches: [ci-tests]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository recursively
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies on Linux
      if: runner.os == 'Linux'
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get install -y xvfb wine32

    - name: Build on Linux
      if: runner.os == 'Linux'
      run: |
        python3 setup.py
        rm -Rf ./wine
        WINEPREFIX=~/.wine32 WINEARCH=win32 xvfb-run wineboot
        WINEPREFIX=~/.wine32 WINEARCH=win32 xvfb-run wine cmd /c build.bat

    - name: Build on Windows
      if: runner.os == 'Windows'
      run: |
        python setup.py
        build.bat

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows_vc6_main_exe
        path: build_vc6/Release/decomp_main.exe
